<table>
<thead>
	<th>*</th><th>1V</th><th>1H</th><th>2V</th><th>2H</th><th>3V</th><th>3H</th><th>4V</th><th>4H</th><th>5V</th><th>5H</th><th>6V</th><th>6H</th>
</thead>
<tr>
	<th>A</th>
	<td><?=$wheeldim->LA1;?></td>
	<td><?=$wheeldim->RA1;?></td>
	<td><?=$wheeldim->LA2;?></td>
	<td><?=$wheeldim->RA2;?></td>
	<td><?=$wheeldim->LA3;?></td>
	<td><?=$wheeldim->RA3;?></td>
	<td><?=$wheeldim->LA4;?></td>
	<td><?=$wheeldim->RA4;?></td>
	<td><?=$wheeldim->LA5;?></td>
	<td><?=$wheeldim->RA5;?></td>
	<td><?=$wheeldim->LA6;?></td>
	<td><?=$wheeldim->RA6;?></td>
</tr>
<tr>
	<th>B</th>
	<td><?=$wheeldim->LB1;?></td>
	<td><?=$wheeldim->RB1;?></td>
	<td><?=$wheeldim->LB2;?></td>
	<td><?=$wheeldim->RB2;?></td>
	<td><?=$wheeldim->LB3;?></td>
	<td><?=$wheeldim->RB3;?></td>
	<td><?=$wheeldim->LB4;?></td>
	<td><?=$wheeldim->RB4;?></td>
	<td><?=$wheeldim->LB5;?></td>
	<td><?=$wheeldim->RB5;?></td>
	<td><?=$wheeldim->LB6;?></td>
	<td><?=$wheeldim->RB6;?></td>
</tr>
<tr>
	<th>C</th>
	<td><?=$wheeldim->LC1;?></td>
	<td><?=$wheeldim->RC1;?></td>
	<td><?=$wheeldim->LC2;?></td>
	<td><?=$wheeldim->RC2;?></td>
	<td><?=$wheeldim->LC3;?></td>
	<td><?=$wheeldim->RC3;?></td>
	<td><?=$wheeldim->LC4;?></td>
	<td><?=$wheeldim->RC4;?></td>
	<td><?=$wheeldim->LC5;?></td>
	<td><?=$wheeldim->RC5;?></td>
	<td><?=$wheeldim->LC6;?></td>
	<td><?=$wheeldim->RC6;?></td>
</tr>
<tr>
	<th>D</th>
	<td><?=$wheeldim->LD1;?></td>
	<td><?=$wheeldim->RD1;?></td>
	<td><?=$wheeldim->LD2;?></td>
	<td><?=$wheeldim->RD2;?></td>
	<td><?=$wheeldim->LD3;?></td>
	<td><?=$wheeldim->RD3;?></td>
	<td><?=$wheeldim->LD4;?></td>
	<td><?=$wheeldim->RD4;?></td>
	<td><?=$wheeldim->LD5;?></td>
	<td><?=$wheeldim->RD5;?></td>
	<td><?=$wheeldim->LD6;?></td>
	<td><?=$wheeldim->RD6;?></td>
</tr>
</table>